### ISSUE TITLE
Menu closes when sub menu item is clicked

### ISSUE THREAD

**Issue by VeilsideGX** [cbfranca/vertical-responsive-menu#11]
Hi there,

I hope you can help me, I can't seem to find where to change it so that the menu/sub menu stays opened when you click on a sub menu item.

**Comment by cbfranca** [comment]
Please, look at issue #5

**Comment by VeilsideGX** [comment]
Can you please give an example of this instance?

**Comment by cbfranca** [comment]
@VeilsideGX please update package and try again.

**Comment by VeilsideGX** [comment]
Thanks man this is how it's supposed to work. Let's see if I can make the __active class work now with parent expanded.
