### ISSUE TITLE
SCSS variable

### ISSUE THREAD

**Issue by droopygit** [cbfranca/vertical-responsive-menu#9]
Hi,

I can't change vertical-responsive-menu variable in my own scss (like I do with bootstrap for example). Can you you tell us how to achieve this?

Thank you,

Yann.

**Comment by cbfranca** [comment]
You need to ensure that the overrides are declared after the menu's css.

**Comment by droopygit** [comment]
I'm using SCSS so I need to override the variable before.

**Comment by cbfranca** [comment]
The override need to be declared after the main file. The only way to do what you want is using the !important, but is a really bad practice.

**Comment by droopygit** [comment]
SCSS not CSS

**Comment by cbfranca** [comment]
I know, but the order of import of SCSS will make a difference. show me how you're doing,

**Comment by droopygit** [comment]
OK, I import my _variables.scss
@import '_variables';

Then I import my vertical-responsive-menu.scss (and others lib like bootstrap):
@import '../bower_components/bootstrap-sass/assets/stylesheets/_bootstrap';
@import '../bower_components/vertical-responsive-menu/src/sass/vertical-responsive-menu';

In my _variables, if I set a vertical-responsive-menu variable like this
$menu_link_font_size: 18px;

In my css I always get 
.menu--link {
    overflow: hidden;
    font-size: .875rem;
    text-decoration: none;
    font-weight: 400;
    white-space: nowrap;
    cursor: pointer;
}

No problem with bootstrap... Where I'm wrong?

**Comment by cbfranca** [comment]
You need to import your variables after responsive-left-menu:

@import '../bower_components/vertical-responsive-menu/src/sass/vertical-responsive-menu';
@import variables;

**Comment by droopygit** [comment]
I have the same problem with this config.
https://discourse.roots.io/t/how-to-override-boostrap-variables-in-sass/3729/3

**Comment by cbfranca** [comment]
@marcelo-ribeiro Can you help him?

**Comment by cbfranca** [comment]
@droopygit did you solved this situation ?

**Comment by droopygit** [comment]
I had to override styles with my own values like in pure css...
